name: "Build-A-Badge"
description: "Creates dynamic and customizable README badges using shields.io/endpoint"
branding:
  icon: "shield"
  color: "blue"
inputs:
  filename:
    description: "The filename to use in the wiki for storing the JSON badge data"
    required: false
    default: ${{ github.workflow }}
  label:
    description: "The left text, or the empty string to omit the left side of the badge"
    required: true
  message:
    description: "The right text"
    required: true
  color:
    description: "The right color"
    required: false
    default: ""
  labelColor:
    description: "The left color"
    required: false
    default: ""
  namedLogo:
    description: "Logo supported by Shields"
    required: false
    default: ""
  style:
    description: "The default template to use"
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - name: Check out repo
      uses: actions/checkout@v3
    - name: Output user details
      id: user_details
      run: |
        echo "::set-output name=username::$(git log -n 1 --pretty=format:%an)"
        echo "::set-output name=email::$(git log -n 1 --pretty=format:%ae)"
      shell: bash
    - name: Check out wiki
      uses: actions/checkout@v3
      with:
        repository: "${{ github.repository }}.wiki"
        path: wiki
    - name: Update wiki
      run: |
        BADGE_JSON="{\"schemaVersion\":1,\"label\":\"${{ inputs.label }}\",\"message\":\"${{ inputs.message }}\""
        declare -A OPTIONAL_PARAMETERS_ARRAY
        OPTIONAL_PARAMETERS_ARRAY["color"]=${{ inputs.color }}
        OPTIONAL_PARAMETERS_ARRAY["labelColor"]=${{ inputs.labelColor }}
        OPTIONAL_PARAMETERS_ARRAY["namedLogo"]=${{ inputs.namedLogo }}
        OPTIONAL_PARAMETERS_ARRAY["style"]=${{ inputs.style }}
        for key in ${!OPTIONAL_PARAMETERS_ARRAY[@]}; do
          if [[ -n "${OPTIONAL_PARAMETERS_ARRAY[${key}]}" ]]; then
            BADGE_JSON="$BADGE_JSON,\"$key\":\"${OPTIONAL_PARAMETERS_ARRAY[${key}]}\""
          fi
        done
        BADGE_JSON="$BADGE_JSON}"
        cd ./wiki
        echo $BADGE_JSON > "${{ inputs.filename }}.md"
        if [[ -n $(git status --porcelain) ]]; then
          git config user.name ${{ steps.user_details.outputs.username }}
          git config user.email ${{ steps.user_details.outputs.email }}
          git add -A
          git commit -m "update from workflow ${{ github.workflow }}"
          git push
        fi
        cd ..
      shell: bash
