name: Create Build-A-Badge badges
on: [push]
jobs:
  build-a-badge-badges:
    name: Build-A-Badge badges
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo with all tags
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Output latest release
        id: latest_release
        run: echo "::set-output name=value::$(git describe --tags --abbrev=0)"
      - name: Build-A-Badge latest release
        uses: peterrhodesdev/build-a-badge@v1.1.1
        with:
          filename: build-a-badge-latest-release-badge
          label: "Latest release"
          message: ${{ steps.latest_release.outputs.value }}
          color: green
      - name: Output license
        id: license
        run: echo "::set-output name=value::$(head -n 1 LICENSE | sed -e 's/\( License\)*$//')"
      - name: Build-A-Badge license
        uses: peterrhodesdev/build-a-badge@v1.1.1
        with:
          filename: build-a-badge-license-badge
          label: "License"
          message: ${{ steps.license.outputs.value }}
          color: yellow
      - name: Build-A-Badge marketplace
        uses: peterrhodesdev/build-a-badge@v1.1.1
        with:
          filename: build-a-badge-marketplace-badge
          label: "Marketplace"
          message: "Build-A-Badge"
          color: blue
          namedLogo: GitHub