name: Create Build-A-Badge badges
on: [push]
jobs:
  build-a-badge-badges:
    name: Build-A-Badge badges
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo with all tags
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Output latest release
        id: latest_release
        run: echo "::set-output name=value::$(git describe --tags --abbrev=0)"
      - name: Output license
        id: license
        run: echo "::set-output name=value::$(head -n 1 LICENSE | sed -e 's/\( License\)*$//')"
      - name: Build-A-Badge
        uses: peterrhodesdev/build-a-badge@v1.3.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filename: |
            (
              "build-a-badge-latest-release-badge"
              "build-a-badge-license-badge"
              "build-a-badge-marketplace-badge"
            )
          label: |
            (
              "Latest release"
              "License"
              "Marketplace"
            )
          message: |
            (
              "${{ steps.latest_release.outputs.value }}"
              "${{ steps.license.outputs.value }}"
              "Build-A-Badge"
            )
          color: |
            (
              "green"
              "yellow"
              "blue"
            )
          namedLogo: |
            (
              ""
              ""
              "GitHub"
            )
