name: Create Build-A-Badge badges
on: [push]
jobs:
  build-a-badge-badges:
    name: Build-A-Badge badges job
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Build-A-Badge latest release
        uses: peterrhodesdev/build-a-badge@v1.1.1
        with:
          filename: build-a-badge-latest-release-badge
          label: "Lastest release"
          message: $(git describe --abbrev=0 --tags)
          color: green
      - name: Build-A-Badge license
        uses: peterrhodesdev/build-a-badge@v1.1.1
        with:
          filename: build-a-badge-license-badge
          label: "License"
          message: $(head -n 1 LICENSE | sed -e 's/\( License\)*$//')
          color: yellow
      - name: Build-A-Badge license
        uses: peterrhodesdev/build-a-badge@v1.1.1
        with:
          filename: build-a-badge-marketplace-badge
          label: "Marketplace"
          message: "Build-A-Badge"
          color: blue