name: Create last commit badge
on: [push]
jobs:
  last-commit-badge:
    name: Last commit badge job
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Build-A-Badge
        uses: peterrhodesdev/build-a-badge@v1.1.1
        with:
          filename: last-commit-badge
          label: "Last commit"
          message: $(git log -1 --format=%cd)
          color: blue